<?php
/** @var \SBrands\Blog\ViewModel\BlogList $viewModel */
$viewModel = $block->getData('view_model');
$posts = $viewModel->getBlogPosts();
?>



<div class="blog-list">
    <?php if ($posts->getSize()): ?>
        <?php foreach ($posts as $post): ?>
            <div class="post-item">
                <h3>
                    <a href="<?= $block->getUrl('blog/view/index', ['id' => $post->getId()]) ?>">
                        <?= $block->escapeHtml($post->getTitle()) ?>
                    </a>
                </h3>
                <small><?= $block->escapeHtml($post->getCreatedAt()) ?></small>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p>No blog posts found. Time to add some to the database!</p>
    <?php endif; ?>
</div>
